### 데이터 다루기 기초
#### numpy
- 수치 기반 라이브러리
- 고속 수학 처리 라이브러리로 벡터 연산에 강함
- 모든 원소를 동일 자료형으로 변환
 - 배열을 제공
 - [1, 2, "3", "4.5"] -(변환)-> [1, 2, 3, 4.5]
- 각종 수학함수 제공

In [1]:
#라이브러리 호출
import numpy as np

In [7]:
# 넘파이 배열 생성
ar1 = np.array([0,1,2,3])
type(ar)

numpy.ndarray

In [6]:
# 묵시적 동일 데이터 형변환
ar = np.array([0,"1","2",3])
print(ar)
print(type(ar))
ar

['0' '1' '2' '3']
<class 'numpy.ndarray'>


array(['0', '1', '2', '3'], dtype='<U11')

In [11]:
result=[]
for i in ar1:
    result.append(i*2)
print(result)
type(result)

[0, 2, 4, 6]


list

In [12]:
result1=result*2
result1

[0, 2, 4, 6, 0, 2, 4, 6]

In [16]:
# 행렬의 상수곱
resNp = np.array(result)
result3 = resNp*2
result3

array([ 0,  4,  8, 12])

In [20]:
# 행렬의 덧셈
# 같은 차수에 맞는 수끼리 더한 행렬 생성
print(ar1)
print(resNp)
resAr = ar1 + resNp
resAr

[0 1 2 3]
[0 2 4 6]


array([0, 3, 6, 9])

In [23]:
# 행렬의 비교
resComparison = ar1>2
resComparison

array([False, False, False,  True])

In [26]:
# 행렬의 성질
print(np.ndim(ar1), "차원 행렬이며", len(ar1), "개의 원소를 가지고 있습니다")

1 차원 행렬이며 4 개의 원소를 가지고 있습니다


In [29]:
# 행렬의 곱 : 동일차원 동일원소 갯수일 때
ar11 = np.array([1, 2, 3])
ar12 = np.array([2, 3, 4])
ar11*ar2

array([ 2,  6, 12])

In [35]:
ar21 = np.array([[1], [2], [3], [4]])
print(np.ndim(ar21), "차원 행렬이며", len(ar21), "개의 원소를 가지고 있습니다")
ar21

2 차원 행렬이며 4 개의 원소를 가지고 있습니다


array([[1],
       [2],
       [3],
       [4]])

In [37]:
ar11*ar21

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [39]:
# 브로드캐스팅
print(ar11)
print(ar21)
ar11+ar21

[1 2 3]
[[1]
 [2]
 [3]
 [4]]


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [43]:
### 2차원 행렬 연산
ar22=np.array([[1,2], [3,4]])
ar23=np.array([[1,2], [3,4]])
ar22*ar23

array([[ 1,  4],
       [ 9, 16]])

In [48]:
#### 3차원 행렬
ar31 = np.array([[[1,2], [3,4]],[[4,5],[6,7]]])
print(np.ndim(ar31), "차원 행렬이며", len(ar31), "개의 원소를 가지고 있습니다")
for i in enumerate(ar31):
    print(i)

3 차원 행렬이며 2 개의 원소를 가지고 있습니다
(0, array([[1, 2],
       [3, 4]]))
(1, array([[4, 5],
       [6, 7]]))


In [64]:
# 수학적 행렬 계산 형태인 벡터의 내적 형태가 아닌 
# 단순하게 동일 위치에 있는 요소끼리 곱한다
ar21 = np.array([[5,6], [7,8]])
ar22 = np.array([[1,2], [3,4]])
print(ar21)
print(ar22)
print("#"*15, '행렬의 곱[동일 위치에 있는 요소끼리 곱한다]', "#"*15)
print(ar21*ar22)
print("#"*15, '벡터내적', "#"*15)
print(np.dot(ar21,ar22))

[[5 6]
 [7 8]]
[[1 2]
 [3 4]]
############### 행렬의 곱[동일 위치에 있는 요소끼리 곱한다] ###############
[[ 5 12]
 [21 32]]
############### 벡터내적 ###############
[[23 34]
 [31 46]]


In [66]:
ar21=np.array([[5,6], [7,8], [9,10]])
print("#"*15, '슬라이싱[인덱스1번째부터]', "#"*15)
print(ar21[1:]) # 슬라이싱
print("#"*15, '인덱싱[인덱스1번]', "#"*15)
print(ar21[1]) # 인덱싱
print("#"*15, '- 슬라이싱[인덱스 -1번째부터]', "#"*15)
print(ar21[-1:])

############### 슬라이싱[인덱스1번째부터] ###############
[[ 7  8]
 [ 9 10]]
############### 인덱싱[인덱스1번] ###############
[7 8]
############### - 슬라이싱[인덱스 -1번째부터] ###############
[[ 9 10]]
